### ISSUE TITLE
Insert query gives error

### ISSUE THREAD

**Issue by pkendre** [Automattic/php-thrift-sql#17]
Hi, 
first of all thanks a lot for sharing this repository. It worked flawlessly. I am able to connect and run few sql like show tables, show databases and select sqls. I am trying to do Insert operation now.
I am using Ambari and HDP 2.4 (Hive 1.2) and I have enabled the ACID property in order to enable the insert, update and delete.

While running Insert sql it is gicing me following error

 _$sql = "INSERT INTO TABLE mydb.variables_new2 (id, a_cost, b_cost) VALUES (2, 10, 20)";
 $hiveTables = $hive
    ->setSasl( true ) 
    ->connect()
    ->query( $sql );
print_r( $hiveTables );_

Output is:
_ThriftSQL\HiveQuery Object ( [_resp:ThriftSQL\HiveQuery:private] => ThriftSQL\TExecuteStatementResp Object ( [status] => ThriftSQL\TStatus Object ( [statusCode] => 0 [infoMessages] => [sqlState] => [errorCode] => [errorMessage] => ) [operationHandle] => ThriftSQL\TOperationHandle Object ( [operationId] => ThriftSQL\THandleIdentifier Object ( [guid] => [��R!CN�����},�� [secret] => _�ڝ�@̲�:S��� ) [operationType] => 0 [hasResultSet] => [modifiedRowCount] => ) ) [_client:ThriftSQL\HiveQuery:private] => ThriftSQL\TCLIServiceClient Object ( [input_:protected] => Thrift\Protocol\TBinaryProtocol Object ( [strictRead_:protected] => [strictWrite_:protected] => 1 [trans_:protected] => Thrift\Transport\TSaslClientTransport Object ( [transport_:Thrift\Transport\TSaslClientTransport:private] => Thrift\Transport\TSocket Object ( [handle_:Thrift\Transport\TSocket:private] => Resource id #25 [host_:protected] => 172.16.1.150 [port_:protected] => 10000 [sendTimeoutSec_:Thrift\Transport\TSocket:private] => 0 [sendTimeoutUsec_:Thrift\Transport\TSocket:private] => 100000 [recvTimeoutSec_:Thrift\Transport\TSocket:private] => 0 [recvTimeoutUsec_:Thrift\Transport\TSocket:private] => 750000 [persist_:protected] => [debug_:protected] => [debugHandler_:protected] => error_log ) [username_:protected] => hive [password_:protected] => hive [saslComplete_:Thrift\Transport\TSaslClientTransport:private] => 1 [readBuffer_:Thrift\Transport\TSaslClientTransport:private] => [writeBuffer_:Thrift\Transport\TSaslClientTransport:private] => ) ) [output_:protected] => Thrift\Protocol\TBinaryProtocol Object ( [strictRead_:protected] => [strictWrite_:protected] => 1 [trans_:protected] => Thrift\Transport\TSaslClientTransport Object ( [transport_:Thrift\Transport\TSaslClientTransport:private] => Thrift\Transport\TSocket Object ( [handle_:Thrift\Transport\TSocket:private] => Resource id #25 [host_:protected] => 172.16.1.150 [port_:protected] => 10000 [sendTimeoutSec_:Thrift\Transport\TSocket:private] => 0 [sendTimeoutUsec_:Thrift\Transport\TSocket:private] => 100000 [recvTimeoutSec_:Thrift\Transport\TSocket:private] => 0 [recvTimeoutUsec_:Thrift\Transport\TSocket:private] => 750000 [persist_:protected] => [debug_:protected] => [debugHandler_:protected] => error_log ) [username_:protected] => hive [password_:protected] => hive [saslComplete_:Thrift\Transport\TSaslClientTransport:private] => 1 [readBuffer_:Thrift\Transport\TSaslClientTransport:private] => [writeBuffer_:Thrift\Transport\TSaslClientTransport:private] => ) ) [seqid_:protected] => 0 ) [_ready:ThriftSQL\HiveQuery:private] => )_ 

I have 1 question, the function queryAndFetchAll() worked for Select sqls. Shall I use the same function to run Insert, update and delete command or I have to use any other function. 
Where I can see list of all functions that you have created in this library(phar).

I am trying since last week to make it work.

Please help. 

Thanks in advance,
Paresh Kendre (kendreparesh@gmail.com)

**Comment by pkendre** [comment]
Please help. you are the only hope.

**Comment by xyu** [comment]
Queries are executed on Hive/Impala in an async / non-blocking manner, the Thrift connection is maintained during query execution and can be used to check if results are ready however it does not block execution as the state of what's happening is returned immediately. For what you are doing you want to make sure you wait and block further execution until the insert is done so you want to do something like this instead:

```php
$sql = "INSERT INTO TABLE mydb.variables_new2 (id, a_cost, b_cost) VALUES (2, 10, 20)";

$hive
  ->setSasl( true )
  ->connect()
  ->query( $sql )
  ->wait();

echo "Finished insert!"
```
