### ISSUE TITLE
Composer install phar not found during deployment.

### ISSUE THREAD

**Issue by Bartheyrman22** [Automattic/php-thrift-sql#20]
The Path in autoload_static is set to a non-relative phar location. This gives problems when deploying the code to a server where the absolute location can differ from the original one.

public static $files = array (
        '2cffec82183ee1cea088009cef9a6fc3' => __DIR__ . '/..' . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
        'c972dff9f16ac280b1304f543e741e8a' => __DIR__ . '/..' . '/greenlion/php-sql-parser/src/PHPSQLParser/PHPSQLCreator.php',
        'd6cde5c960e16951227fd8cd2000d80a' => __DIR__ . '/..' . '/greenlion/php-sql-parser/src/PHPSQLParser/PHPSQLParser.php',
        '5eb9c05cf55211ba85c38aa136f5e17e' => 'phar://C:\\Users\\User1\\Documents\\PhpstormProjects\\querotails\\vendor/automattic/php-thrift-sql/ThriftSQL.phar',
    );

**Comment by janblahamall** [comment]
I have the same problem with ThriftSQL.phar :/

**Comment by xyu** [comment]
I think this is related to composer/composer#5564 and is fixed in v1.2+ closing this issue.
