### ISSUE TITLE
can not connect to hiveserver2

### ISSUE THREAD

**Issue by lixiyu** [Automattic/php-thrift-sql#22]
I can connect to hiveserver2 in beeline whith  beeline> !connect jdbc:hive2://192.168.1.110:10010
but cannot conncet to hiveserver2 whith code blow (there are no username and password):
` 
 $hive = new \ThriftSQL\Hive( '192.168.1.110',10010);                                                                                                                                                   
  $hiveTables = $hive
    ->setSasl( false ) /* To turn SASL auth off, on by default */
    ->connect()
    ->queryAndFetchAll( 'SHOW TABLES' );
  print_r( $hiveTables );
`

and I got the error : 
`PHP Fatal error:  Uncaught Thrift\Exception\TException: TSocket: Could not connect to 192.168.1.110:10010 (Connection refused [111]) in phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Thrift/Transport/TSocket.php:235
Stack trace:
#0 phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/ThriftSQL/Hive.php(47): Thrift\Transport\TSocket->open()
#1 /home/lixiyu/code/php-thrift-sql/example.php(10): ThriftSQL\Hive->connect()
#2 {main}
  thrown in phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Thrift/Transport/TSocket.php on line 235`

can somebody help me ?

**Comment by lixiyu** [comment]
may be is hiveserver2 close it self. after I restart hiveserver2, I got error bellow : 
`PHP Fatal error:  Uncaught Thrift\Exception\TTransportException: TSocket read 0 bytes in phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Thrift/Transport/TSocket.php:269
Stack trace:
#0 phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Thrift/Transport/TTransport.php(74): Thrift\Transport\TSocket->read(67108844)
#1 phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Thrift/Protocol/TBinaryProtocol.php(212): Thrift\Transport\TTransport->readAll(67108864)
#2 phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Packages/TCLIService/TCLIService.php(162): Thrift\Protocol\TBinaryProtocol->readMessageBegin(NULL, 0, 0)
#3 phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Packages/TCLIService/TCLIService.php(131): ThriftSQL\TCLIServiceClient->recv_OpenSession()
#4 phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/ThriftSQL/Hive.php(62): ThriftSQL\TCLIServiceClient->OpenSession(Object(ThriftSQL\TOpenSessionReq))
#5 /home/lixiyu/code/php-thrift-sql/example.php(10): ThriftSQL\Hive->connect()
#6 {main}
  thrown in phar:///home/lixiyu/code/php-thrift-sql/ThriftSQL.phar/Thrift/Transport/TSocket.php on line 269`

**Comment by lixiyu** [comment]
问题解决了。算是hive配置的问题吧。有人说 PHP的框架不支持SASL，或者我不会用。
修改 hive-site.xml 这个配置 然后重启hiveserver2就 OK 了，但是改了之后 beeline 不能连上来了。
`<property><name>hive.server2.authentication</name><value>NOSASL</value></property>`
（这个值默认是 NULL ，必须改成 NOSASL 才能用这个框架按照我上面的用法连接成功）

参考答案：
http://stackoverflow.com/questions/15415904/requests-hang-when-using-hiveserver2-thrift-java-client

**Comment by DYFeng** [comment]
```php
$hive = new \ThriftSQL\Hive('stats-hadoop11', 10000, 'yeyifeng','fake_password');
$hive->setSasl(true);
var_dump($hive->connect()->queryAndFetchAll('show tables;')) ;
```
Works for me.Just using a fake pasword.

But my hive server does not have this configure.
` <property><name>hive.server2.authentication</name><value>NOSASL</value></property>`

**Comment by mariedavis-abn** [comment]
I was trying to connect with Username Authentication for my Hiveserver2. I was getting an error for "tsocket read 0 bytes". Creating a fake username and password worked for me.
