### ISSUE TITLE
A way to perform alter table to add partition is needed.

### ISSUE THREAD

**Issue by luchiana** [Automattic/php-thrift-sql#27]
Hello I would like a way to perform an alter table to add a partition.
Would be great if your answer is "it already exists, this is how you use it :) "
Thank you.

**Comment by xyu** [comment]
This library simply connects to either Hive or Impala, once connected you can execute any queries you have permissions for including DDL statements to add or remove partitions:

https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-AlterTable/Partition/Column
