### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by markuswoessner** [Automattic/php-thrift-sql#30]
Hi,

we would like to use this library in our project and wonder if the library itself and bundled 3rd party libraries are compatible with PHP 7.1.

Do you have any experiences specific to running the library against PHP >= 7.1 ?

We appreciate your work very much and thank you in advance for your response.

Kind regards,

Markus Wößner

ADITION technologies
Freiburg, Germany

**Comment by xyu** [comment]
Hello @markuswoessner we currently run this library in production with PHP 7.3.5 without issues.
