### ISSUE TITLE
TSocket read 0 bytes

### ISSUE THREAD

**Issue by tianhuimin** [Automattic/php-thrift-sql#36]
Exception: **TSocket read 0 bytes**
------------------------------------------------------
try {
            // Try out a Hive query via iterator object
            $hive = new \ThriftSQL\Hive('10.10.0.1', 10000, null, null, 3600 * 24);
            $hiveTables = $hive->connect()->queryAndFetchAll($hive_sql);
...
} catch (\Exception $ex) {
            $message = $ex->getMessage();
}

**Comment by bperson** [comment]
@tianhuimin this looks very much like an issue between your code and your Hive server and not directly with this PHP client.

Tentatively closing, feel free to reopen if you can confirm you're able to connect via `beeline` or another Hive client.
