### ISSUE TITLE
is this  a bug? table exist,bug not found

### ISSUE THREAD

**Issue by danding-s** [Automattic/php-thrift-sql#38]
Exception 'ThriftSQL\Exception' with message 'Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 6:24 Table not found ''

**Comment by bperson** [comment]
This is the kind of error message that's coming straight from Hive, did you double check the table name? is it generated dynamically? Can you execute the exact same query via another client? ( beeline, ... )

Tentatively closing as user error, feel free to reopen if you confirm all of the above worked fine.

**Comment by danding-s** [comment]
I am sure the table exist,but not found,if I try more times, the table can be found

**Comment by bperson** [comment]
We would need some kind of minimally working environment where you're experiencing this error to debug this further. From the looks of it, my first guess would be that another process is dropping / creating that table from the Hive meta store and this is why you're experiencing those issues ... which would be independent from `php-thrift-sql` which is really *just* a PHP client to connect to Hive or Impala.
