### ISSUE TITLE
你好，我执行example.php的时候一直报错Could not connect to，求助！

### ISSUE THREAD

**Issue by shironghui** [Automattic/php-thrift-sql#39]
我改了example.php里的impala连接配置，php example.php时报错（x.x.x.x代替我真实的impala配置）：
Fatal error: Uncaught Thrift\Exception\TException: TSocket: Could not connect to x.x.x.x:21050 (Operation timed out [60]) in phar:///Users/xxx/Code/www/php-thrift-sql/ThriftSQL.phar/Thrift/Transport/TSocket.php:250

example.php里的代码只保留了impala:
<?php
  require_once __DIR__ . '/ThriftSQL.phar';
  // Try out an Impala query via iterator object
  $impala = new \ThriftSQL\Impala( 'x.x.x.x', 21050);
  $impalaTables = $impala
    ->connect()
    ->setOption( 'REQUEST_POOL', 'php' )
    ->setOption( 'MEM_LIMIT', '256mb' )
    ->getIterator( 'SHOW TABLES' );
  foreach( $impalaTables as $rowNum => $row ) {
    print_r( $row );
  }
  $impala->disconnect();
希望得到您的帮助，非常感谢~~~

**Comment by bperson** [comment]
> TSocket: Could not connect to x.x.x.x:21050 (Operation timed out 

Have you tried connecting to that Impala daemon ( x.x.x.x ), on that port ( 21050 ), from the server executing your PHP code through another client?

Tentatively closing, feel free to reopen once you've checked that you're indeed able to connect to that impala daemon from the host executing this PHP code.
