### ISSUE TITLE
make phar的时候一直失败？

### ISSUE THREAD

**Issue by shironghui** [Automattic/php-thrift-sql#40]
![image](https://user-images.githubusercontent.com/3852344/79934254-b9719680-8484-11ea-9c6a-4df84529dc83.png)

Service "TCLIService.TCLIService" has not been defined.
make: *** [impala] Error 1

**Comment by bperson** [comment]
Did you `git submodule init` in the `src-thrift` folder ? This looks a lot like the git submodules in `src-thrift` haven't been downloaded.

**Comment by shironghui** [comment]
3Q

**Comment by shironghui** [comment]
@bperson 
我安装好后，写了个简单的test.php，有两个服务器，一个成功连接，另一个报错然后我试了多次都是报错：
TSocket read 0 bytes,请问知道是什么原因吗？

**Comment by bperson** [comment]
> 我安装好后，写了个简单的test.php，有两个服务器，一个成功连接，另一个报错然后我试了多次都是报错： TSocket read 0 bytes,请问知道是什么原因吗？

( first: I don't understand chinese, so I used an online translation tool so there might be a misunderstanding )

This sounds like a misconfiguration between the host executing `test.php` and your Hive servers. The fact that it worked on one and then stopped is even more a sign that the error is most likely coming from the network in your setup: firewall, proxy ...
