### ISSUE TITLE
Time out problem

### ISSUE THREAD

**Issue by B1u3f331** [Automattic/php-thrift-sql#41]
I use this repository for php to SQL query hiveserver2. But one SQL query task may takes 20 minutes. So there is a time out problem. Can I set the time out limitation and if possible, how to change it？Thanks.

**Comment by bperson** [comment]
the [5th parameter](https://github.com/Automattic/php-thrift-sql/blob/c2d8d83260b8227a5753fdc2d96047676f1b3a20/src/ThriftSQL/Hive.php#L16) when instantiating a new `Hive` instance is used as [the timeout for Rx and Tx](https://github.com/Automattic/php-thrift-sql/blob/c2d8d83260b8227a5753fdc2d96047676f1b3a20/src/ThriftSQL/Hive.php#L45).
