### ISSUE TITLE
make phar error 

### ISSUE THREAD

**Issue by allen0817** [Automattic/php-thrift-sql#42]
error 

[root@qitv2302 bb]# make phar
git submodule update
# Build error codes thrift file
src-thrift/impala/common/thrift/generate_error_codes.py
: No such file or directory
make: *** [impala] Error 127
[root@qitv2302 bb]# ls -a  src-thrift/impala/common/thrift/generate_error_codes.py 
-rwxr-xr-x 1 root 22020 May 16 19:43 src-thrift/impala/common/thrift/generate_error_codes.py

file is haved

**Comment by bperson** [comment]
You need to `git submodule init`
