### ISSUE TITLE
'Required field 'operationHandle' is unset!

### ISSUE THREAD

**Issue by dinnyosz** [Automattic/php-thrift-sql#9]
Hi, 

I try to use your implementation for connecting to a hive cluster, which works as expected with the given sample. But when I try to retrieve anything from hive that needs some map/reduce jobs run, I've got the following exception:
 'Thrift\Exception\TApplicationException' with message 'Required field 'operationHandle' is unset!
Can you help me where should I set this? 

Thx in advance

**Comment by xyu** [comment]
It sounds like this error is coming from [here](https://github.com/Automattic/php-thrift-sql/blob/master/src/ThriftSQL/Hive.php#L108-L113). `operationHandle` should be returned by a successful `TExecuteStatementResp` and used to reference further operations. Can you try logging `$TExecuteStatementResp` and see what's happening with your MR job based queries?

**Comment by xyu** [comment]
Closing stale issue.
